apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-LoadBalancer
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: LoadBalancer
