apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-NodePort
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    name: http
    nodePort: 32000
  type: NodePort
