apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
  name: nginx-deployment
  namespace: giropops
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx-deployment
  strategy: 
    type: RollingUpdate
    rollingUpdate: # valores podem ser passados em valores inteiros para dizer quandos pods podem ultrapassar ou ficar indisponíveis
      maxSurge: 10%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
        - image: nginx:1.15.0
          name: nginx
          resources:
            limits:
              cpu: 0.3
              memory: 256Mi
            requests:
              cpu: 0.3
              memory: 64Mi
