
apiVersion: v1
kind: Pod
metadata:
  name: nginx-https
  labels:
    app: nginx-https
spec:
  containers:
    - name: nginx-https
      image: nginx
      ports:
        - containerPort: 80
        - containerPort: 443
      resources:
        limits:
          cpu: "0.5"
          memory: "256Mi"
        requests:
          cpu: "0.3"
          memory: "128Mi"
      volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-secret
          mountPath: /etc/nginx/tls
  volumes:
    - name: nginx-config
      configMap:
        name: nginx-config
    - name: nginx-secret
      secret:
        secretName: nginx-secret
        items:
          - key: tls.crt
            path: nginx.crt
          - key: tls.key
            path: nginx.key  