apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secrets
  labels:
    name: pod-with-secrets
spec:
  containers:
  - name: pod-with-secrets
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: opaque-secret
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: opaque-secret
          key: password
    ports:
      - containerPort: 80
