apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secrets
  labels:
    name: pod-with-secrets
spec:
  containers:
  - name: pod-with-secrets
    image: <PrivateImageName>
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
  imagePullSecrets:
  - name: dockerhub-secret
